baseURL = 'https://miomiomi.org/'
languageCode = 'ja'
title = "yes, I'm dreaming."

publishDir = "public"

[params]
description = "miomの日常"   # サイトの説明（検索結果に表示される）
author = "mio.m"                         # 作者名
keywords = ["ブログ", "日記", "サウンドアート"]  # 検索キーワード

# 開発用サーバーの設定
[server]
port = 1313                   # 開発用サーバーのポート
watch = true                  # ファイル変更を自動検出